flowchart TD
  src_services_core_service_main_py --> src_models_core_py
  src_controller_main_controller_py --> src_controller_core_controller_py
  src_services_core_service_main_py --> src_services_core_service_rag_py
  src_controller_core_controller_py --> src_services_core_service_main_py
  src_services_core_service_rag_py --> src_models_core_py
  src_controller_core_controller_py --> src_models_core_py
